version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fooddb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/fooddb
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_DIR=/app/uploads
      - S3_ENABLED=false
      - CORS_ORIGINS=http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    working_dir: /app
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  db-data:
